// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdgCF_X3AoEho7zEBCMNR2lha3o0UOeWM',
    appId: '1:510922620421:web:6c92bc2221be9b6365e66c',
    messagingSenderId: '510922620421',
    projectId: 'diciojenipapo-6e050',
    authDomain: 'diciojenipapo-6e050.firebaseapp.com',
    storageBucket: 'diciojenipapo-6e050.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwNO6AfpV-CiFbv5DLwH5uxsdHfR4I-XI',
    appId: '1:510922620421:android:7b499423bcadda0d65e66c',
    messagingSenderId: '510922620421',
    projectId: 'diciojenipapo-6e050',
    storageBucket: 'diciojenipapo-6e050.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR2g5_Mu1Bt1AWDrozzTLTRrgC63TZ69w',
    appId: '1:510922620421:ios:56e037bd31a71c9e65e66c',
    messagingSenderId: '510922620421',
    projectId: 'diciojenipapo-6e050',
    storageBucket: 'diciojenipapo-6e050.firebasestorage.app',
    iosBundleId: 'com.example.diciojenipapo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR2g5_Mu1Bt1AWDrozzTLTRrgC63TZ69w',
    appId: '1:510922620421:ios:56e037bd31a71c9e65e66c',
    messagingSenderId: '510922620421',
    projectId: 'diciojenipapo-6e050',
    storageBucket: 'diciojenipapo-6e050.firebasestorage.app',
    iosBundleId: 'com.example.diciojenipapo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdgCF_X3AoEho7zEBCMNR2lha3o0UOeWM',
    appId: '1:510922620421:web:b3f7cdfc246ede5165e66c',
    messagingSenderId: '510922620421',
    projectId: 'diciojenipapo-6e050',
    authDomain: 'diciojenipapo-6e050.firebaseapp.com',
    storageBucket: 'diciojenipapo-6e050.firebasestorage.app',
  );

}